package com.github.mlangc.wetterfrosch

object HistoryExportCols {
  val Minute = "Minute"
  val Hour = "Hour"
  val Year = "Year"
  val Month = "Month"
  val Day = "Day"
  val TempDailyMin = "Temperature daily min [2 m above gnd]"
  val TempDailyMean = "Temperature daily mean [2 m above gnd]"
  val TempDailyMax = "Temperature daily max [2 m above gnd]"
  val WindGustDailyMin = "Wind Gust daily min [sfc]"
  val TotalPrecipitationDailySum = "Total Precipitation daily sum [sfc]"
  val SnowfallAmountDaily = "Snowfall amount raw daily sum [sfc]"
  val SunshineDurationDailySum = "Sunshine Duration daily sum [sfc]"
  val SunshineDuration = "Sunshine Duration  [sfc]"

  val HighCloudCoverDailyMean = "High Cloud Cover daily mean [high cld lay]"
  val LowCloudCoverDailyMean = "Low Cloud Cover daily mean [low cld lay]"
  val MeanSeaLevelPressureDailyMean = "Mean Sea Level Pressure daily mean [MSL]"
  val MediumCloudCoverDailyMean = "Medium Cloud Cover daily mean [mid cld lay]"
  val RelativeHumidityDailyMean = "Relative Humidity daily mean [2 m above gnd]"
  val WindDirectionDailyMean10m = "Wind Direction daily mean [10 m above gnd]"
  val WindDirectionDailyMean80m = "Wind Direction daily mean [80 m above gnd]"
  val WindDirectionDailyMean900mb = "Wind Direction daily mean [900 mb]"
  val WindGustDailyMean = "Wind Gust daily mean [sfc]"
  val WindSpeedDailyMean10m = "Wind Speed daily mean [10 m above gnd]"
  val WindSpeedDailyMean80m = "Wind Speed daily mean [80 m above gnd]"
  val WindSpeedDailyMean900mb = "Wind Speed daily mean [900 mb]"
  val TotalCloudCoverDailyMean = "Total Cloud Cover daily mean [sfc]"
}
